/**
 * VaultGuard — Audit & Monitoring Lambda Handler
 *
 * Provides audit log querying, user activity tracking, file access history,
 * security alerting, and compliance export capabilities.
 *
 * Includes anomaly detection for:
 * - Revoked user access attempts
 * - Unusual access patterns (bulk downloads, off-hours access)
 * - Repeated permission denials
 *
 * Endpoints:
 * - GET  /vaults/{vaultId}/audit/logs          — Query audit logs with filters
 * - GET  /vaults/{vaultId}/audit/user/{userId} — Get all activity for a user in a vault
 * - GET  /vaults/{vaultId}/audit/file/{path}   — Get all access to a file in a vault
 * - GET  /vaults/{vaultId}/audit/alerts        — Get security alerts for a vault
 * - POST /vaults/{vaultId}/audit/export        — Export audit logs as CSV
 * - POST /vaults/{vaultId}/audit/report        — Legacy alias for CSV export
 */

import { APIGatewayProxyEvent, APIGatewayProxyResult } from 'aws-lambda';
import {
  docClient,
  verifyActiveUser,
  requireOrgId,
  logAudit,
  formatError,
  formatSuccess,
  parseBody,
  getClientIp,
  getUserAgent,
  generateId,
  requireVaultMember,
  UserContext,
  AuditEntry,
  AuthError,
  ValidationError,
  PutCommand,
  QueryCommand,
  AUDIT_TABLE,
  DEFAULT_ORG_SETTINGS,
  getEffectiveOrgSettings,
} from '../shared/utils';
import { FEATURES } from '../shared/edition';

// ─── Configuration ───────────────────────────────────────────────────────────

// Required env var — see shared/utils.ts for rationale on dropping silent fallbacks.
const ALERTS_TABLE = process.env.ALERTS_TABLE!;
const ANOMALY_THRESHOLD_DENIED = parseInt(process.env.ANOMALY_THRESHOLD_DENIED || '5', 10);

/**
 * Soft cap on the retention window for audit-log queries on Community Edition.
 *
 * Pro Edition honors the full `orgSettings.retentionDays` (default 365 days).
 * Community Edition clamps the query window to the most recent 30 days,
 * matching the ProUpsellModal copy and the SERVER_README marketing table.
 *
 * This is a *query-time* cap only — records are still stored per the org's
 * retentionDays and any DynamoDB TTL. CE users can upgrade to Pro to read
 * older entries without re-ingesting data.
 */
export const CE_AUDIT_RETENTION_DAYS = 30;

const ANOMALY_THRESHOLD_BULK = parseInt(process.env.ANOMALY_THRESHOLD_BULK || '50', 10);
const ANOMALY_WINDOW_MINUTES = parseInt(process.env.ANOMALY_WINDOW_MINUTES || '10', 10);
const ANOMALY_THRESHOLD_DISTINCT_IPS = parseInt(process.env.ANOMALY_THRESHOLD_DISTINCT_IPS || '3', 10);
const ANOMALY_THRESHOLD_DISTINCT_PATHS = parseInt(process.env.ANOMALY_THRESHOLD_DISTINCT_PATHS || '12', 10);
const OFF_HOURS_START_HOUR_UTC = parseInt(process.env.OFF_HOURS_START_HOUR_UTC || '20', 10);
const OFF_HOURS_END_HOUR_UTC = parseInt(process.env.OFF_HOURS_END_HOUR_UTC || '6', 10);
const ALLOWED_CORS_ORIGIN = process.env.ALLOWED_CORS_ORIGIN || 'https://admin.example.com';

// ─── Types ───────────────────────────────────────────────────────────────────

/** Security alert generated by anomaly detection. */
interface SecurityAlert {
  id: string;
  orgId: string;
  vaultId: string;
  type: 'revoked_access_attempt' | 'unusual_pattern' | 'bulk_download' | 'repeated_denial' | 'off_hours_access';
  severity: 'low' | 'medium' | 'high' | 'critical';
  userId: string;
  description: string;
  timestamp: string;
  metadata: Record<string, unknown>;
  acknowledged: boolean;
  acknowledgedBy?: string;
  acknowledgedAt?: string;
}

/** Filter parameters for audit log queries. */
interface AuditQueryFilters {
  search?: string;
  userId?: string;
  action?: string;
  resourcePath?: string;
  outcome?: 'success' | 'denied' | 'error';
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: Record<string, unknown>;
}

interface PaginatedResult<T> {
  items: T[];
  nextCursor: string | null;
  lastEvaluatedKey: Record<string, unknown> | null;
}

// ─── Main Handler ────────────────────────────────────────────────────────────

/**
 * Lambda entry point. Routes audit/monitoring requests based on
 * HTTP method and resource path.
 *
 * @param event - API Gateway proxy event
 * @returns API Gateway proxy result with JSON body
 */
export async function handler(event: APIGatewayProxyEvent): Promise<APIGatewayProxyResult> {
  const requestId = event.requestContext?.requestId || generateId();
  const method = event.httpMethod?.toUpperCase();
  const resource = event.resource || '';

  if (!FEATURES.advancedAudit && isAdvancedAuditRoute(method, resource)) {
    return formatError(404, `Route not found: ${method} ${resource}`, requestId);
  }

  try {
    // Authenticate all requests
    const user = await verifyActiveUser(event);
    const vaultId = event.pathParameters?.vaultId || '';

    if (!vaultId) {
      return formatError(400, 'vaultId path parameter is required for audit routes', requestId);
    }

    await requireAuditVaultAdmin(event, user, vaultId, resource);

    switch (true) {
      case method === 'GET' && (resource === '/vaults/{vaultId}/audit/logs' || resource === '/vaults/{vaultId}/audit'):
        return await handleQueryLogs(event, user, vaultId, requestId);

      case method === 'GET' && resource === '/vaults/{vaultId}/audit/user/{userId}':
        return await handleUserActivity(event, user, vaultId, requestId);

      case method === 'GET' && resource === '/vaults/{vaultId}/audit/file/{path+}':
        return await handleFileAccess(event, user, vaultId, requestId);

      case method === 'GET' && resource === '/vaults/{vaultId}/audit/alerts':
        return await handleGetAlerts(event, user, vaultId, requestId);

      case method === 'POST' && (resource === '/vaults/{vaultId}/audit/export' || resource === '/vaults/{vaultId}/audit/report'):
        return await handleExport(event, user, vaultId, requestId);

      default:
        return formatError(404, `Route not found: ${method} ${resource}`, requestId);
    }
  } catch (err: unknown) {
    if (err instanceof AuthError) {
      return formatError(err.statusCode, err.message, requestId);
    }
    if (err instanceof ValidationError) {
      return formatError(err.statusCode, err.message, requestId);
    }

    console.error('[AUDIT_HANDLER_ERROR]', (err as Error).message);
    return formatError(500, 'Internal server error', requestId);
  }
}

function isAdvancedAuditRoute(method: string | undefined, resource: string): boolean {
  return (
    (method === 'GET' && resource === '/vaults/{vaultId}/audit/user/{userId}') ||
    (method === 'GET' && resource === '/vaults/{vaultId}/audit/file/{path+}') ||
    (method === 'GET' && resource === '/vaults/{vaultId}/audit/alerts') ||
    (method === 'POST' && (resource === '/vaults/{vaultId}/audit/export' || resource === '/vaults/{vaultId}/audit/report'))
  );
}

async function requireAuditVaultAdmin(
  event: APIGatewayProxyEvent,
  user: UserContext,
  vaultId: string,
  resource: string
): Promise<void> {
  try {
    await requireVaultMember(user, vaultId, 'admin');
  } catch (err) {
    await logAudit({
      userId: user.userId,
      userEmail: user.email,
      orgId: user.orgId,
      vaultId,
      action: 'audit.access.denied',
      resourcePath: resource || `/vaults/${vaultId}/audit`,
      outcome: 'denied',
      ipAddress: getClientIp(event),
      userAgent: getUserAgent(event),
      metadata: { vaultId, reason: (err as Error).message },
    });
    throw err;
  }
}

// ─── GET /vaults/{vaultId}/audit/logs ────────────────────────────────────────

/**
 * Queries audit logs with flexible filtering.
 *
 * Query Parameters:
 * - userId: Filter by user who performed the action
 * - action: Filter by action type (e.g., 'files.read', 'auth.login')
 * - path: Filter by resource path (prefix match)
 * - outcome: Filter by outcome ('success', 'denied', 'error')
 * - startDate: ISO timestamp for range start
 * - endDate: ISO timestamp for range end
 * - limit: Maximum results (default 100, max 1000)
 * - lastEvaluatedKey: For pagination
 *
 * @param event - API Gateway event with query parameters
 * @param user - Authenticated admin user
 * @param requestId - Request ID for tracing
 * @returns Paginated audit log entries matching filters
 */
async function handleQueryLogs(
  event: APIGatewayProxyEvent,
  user: UserContext,
  vaultId: string,
  requestId: string
): Promise<APIGatewayProxyResult> {
  const params = event.queryStringParameters || {};
  const limit = clampLimit(params.limit, 100, 1000);
  const retentionWindow = await applyRetentionWindow(
    user.orgId,
    normalizeStartTimestamp(params.startDate),
    normalizeEndTimestamp(params.endDate)
  );

  const filters: AuditQueryFilters = {
    search: params.search || params.q,
    userId: params.userId,
    action: params.action,
    resourcePath: params.path,
    outcome: params.outcome as AuditQueryFilters['outcome'],
    startDate: retentionWindow.startDate,
    endDate: retentionWindow.endDate,
    limit,
    cursor: decodeCursor(params.cursor),
  };
  const query = buildVaultAuditQuery(user.orgId, vaultId, filters);
  const result = await queryAuditIndex<AuditEntry>({
    indexName: 'vaultId-index',
    keyConditionExpression: query.keyConditionExpression,
    expressionAttributeValues: query.expressionAttributeValues,
    expressionAttributeNames: query.expressionAttributeNames,
    filterExpression: query.filterExpression,
    limit,
    cursor: filters.cursor,
  });

  return formatSuccess(
    200,
    {
      entries: result.items,
      count: result.items.length,
      filters,
      nextCursor: result.nextCursor,
      lastEvaluatedKey: result.lastEvaluatedKey,
    },
    requestId
  );
}

// ─── GET /vaults/{vaultId}/audit/user/{userId} ───────────────────────────────

/**
 * Returns all audit activity for a specific user.
 * Shows a complete timeline of their actions in the vault.
 *
 * Query Parameters:
 * - startDate: Filter from this date (optional)
 * - endDate: Filter to this date (optional)
 * - limit: Maximum results (default 200)
 *
 * @param event - API Gateway event with userId path parameter
 * @param user - Authenticated admin user
 * @param requestId - Request ID for tracing
 * @returns User's complete activity timeline
 */
async function handleUserActivity(
  event: APIGatewayProxyEvent,
  user: UserContext,
  vaultId: string,
  requestId: string
): Promise<APIGatewayProxyResult> {
  const targetUserId = event.pathParameters?.userId;

  if (!targetUserId) {
    return formatError(400, 'userId path parameter is required', requestId);
  }

  const params = event.queryStringParameters || {};
  const limit = clampLimit(params.limit, 200, 1000);
  const retentionWindow = await applyRetentionWindow(
    user.orgId,
    normalizeStartTimestamp(params.startDate),
    normalizeEndTimestamp(params.endDate)
  );
  const startDate = retentionWindow.startDate;
  const endDate = retentionWindow.endDate;
  const cursor = decodeCursor(params.cursor);
  const query = buildTimeBoundKeyCondition('vaultId = :vaultId', {
    ':vaultId': vaultId,
  }, startDate, endDate);
  query.filterParts.push('orgId = :orgId');
  query.expressionAttributeValues[':orgId'] = user.orgId;
  query.filterParts.push('userId = :userId');
  query.expressionAttributeValues[':userId'] = targetUserId;

  const result = await queryAuditIndex<AuditEntry>({
    indexName: 'vaultId-index',
    keyConditionExpression: query.keyConditionExpression,
    expressionAttributeValues: query.expressionAttributeValues,
    expressionAttributeNames: query.expressionAttributeNames,
    filterExpression: query.filterParts.join(' AND '),
    limit,
    cursor,
  });

  // Generate activity summary
  const summary = generateActivitySummary(result.items);

  return formatSuccess(
    200,
    {
      userId: targetUserId,
      entries: result.items,
      count: result.items.length,
      summary,
      nextCursor: result.nextCursor,
      lastEvaluatedKey: result.lastEvaluatedKey,
    },
    requestId
  );
}

// ─── GET /vaults/{vaultId}/audit/file/{path} ─────────────────────────────────

/**
 * Returns all access records for a specific file path.
 * Shows who accessed the file, when, and what actions were performed.
 *
 * Query Parameters:
 * - startDate: Filter from this date (optional)
 * - endDate: Filter to this date (optional)
 * - limit: Maximum results (default 200)
 *
 * @param event - API Gateway event with file path parameter
 * @param user - Authenticated admin user
 * @param requestId - Request ID for tracing
 * @returns File access history with user details
 */
async function handleFileAccess(
  event: APIGatewayProxyEvent,
  user: UserContext,
  vaultId: string,
  requestId: string
): Promise<APIGatewayProxyResult> {
  const filePath = '/' + decodeURIComponent(event.pathParameters?.path || '');

  if (filePath === '/') {
    return formatError(400, 'File path is required', requestId);
  }

  const params = event.queryStringParameters || {};
  const limit = clampLimit(params.limit, 200, 1000);
  const retentionWindow = await applyRetentionWindow(
    user.orgId,
    normalizeStartTimestamp(params.startDate),
    normalizeEndTimestamp(params.endDate)
  );
  const startDate = retentionWindow.startDate;
  const endDate = retentionWindow.endDate;
  const cursor = decodeCursor(params.cursor);
  const query = buildTimeBoundKeyCondition('resourcePath = :path', {
    ':path': filePath,
  }, startDate, endDate);
  query.filterParts.push('orgId = :orgId');
  query.expressionAttributeValues[':orgId'] = user.orgId;
  query.filterParts.push('vaultId = :vaultId');
  query.expressionAttributeValues[':vaultId'] = vaultId;

  const result = await queryAuditIndex<AuditEntry>({
    indexName: 'resourcePath-index',
    keyConditionExpression: query.keyConditionExpression,
    expressionAttributeValues: query.expressionAttributeValues,
    expressionAttributeNames: query.expressionAttributeNames,
    filterExpression: query.filterParts.join(' AND '),
    limit,
    cursor,
  });

  // Summarize unique users who accessed this file
  const uniqueUsers = [...new Set(result.items.map((e) => e.userId))];
  const actionBreakdown = result.items.reduce((acc, e) => {
    acc[e.action] = (acc[e.action] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  return formatSuccess(
    200,
    {
      path: filePath,
      entries: result.items,
      count: result.items.length,
      uniqueUsers,
      actionBreakdown,
      nextCursor: result.nextCursor,
      lastEvaluatedKey: result.lastEvaluatedKey,
    },
    requestId
  );
}

// ─── GET /vaults/{vaultId}/audit/alerts ──────────────────────────────────────

/**
 * Returns security alerts generated by the anomaly detection system.
 *
 * Alert types:
 * - revoked_access_attempt: A user whose access was revoked tried to authenticate
 * - unusual_pattern: Abnormal behavior detected (time, volume, pattern)
 * - bulk_download: Excessive file reads in a short window
 * - repeated_denial: Multiple permission-denied events for same user
 * - off_hours_access: Access attempts outside normal working hours
 *
 * Query Parameters:
 * - severity: Filter by severity level
 * - type: Filter by alert type
 * - acknowledged: 'true' or 'false' to filter by acknowledgment status
 * - limit: Maximum results (default 50)
 *
 * @param event - API Gateway event with optional filters
 * @param user - Authenticated admin user
 * @param requestId - Request ID for tracing
 * @returns List of security alerts
 */
async function handleGetAlerts(
  event: APIGatewayProxyEvent,
  user: UserContext,
  vaultId: string,
  requestId: string
): Promise<APIGatewayProxyResult> {
  const params = event.queryStringParameters || {};
  const limit = clampLimit(params.limit, 50, 500);
  const expressionValues: Record<string, unknown> = { ':orgId': user.orgId, ':vaultId': vaultId };
  const expressionNames: Record<string, string> = {};
  const filterParts: string[] = ['vaultId = :vaultId'];

  if (params.severity) {
    filterParts.push('severity = :severity');
    expressionValues[':severity'] = params.severity;
  }

  if (params.type) {
    filterParts.push('#type = :type');
    expressionValues[':type'] = params.type;
    expressionNames['#type'] = 'type';
  }

  if (params.acknowledged !== undefined) {
    filterParts.push('acknowledged = :ack');
    expressionValues[':ack'] = params.acknowledged === 'true';
  }

  await detectAnomalies(user, vaultId);

  const result = await queryAlerts({
    expressionAttributeValues: expressionValues,
    expressionAttributeNames: expressionNames,
    filterExpression: filterParts.length > 0 ? filterParts.join(' AND ') : undefined,
    limit,
    cursor: decodeCursor(params.cursor),
  });
  const alerts = sortAlerts(result.items);

  return formatSuccess(
    200,
    {
      alerts,
      count: alerts.length,
      unacknowledged: alerts.filter((a) => !a.acknowledged).length,
      nextCursor: result.nextCursor,
      lastEvaluatedKey: result.lastEvaluatedKey,
    },
    requestId
  );
}

// ─── POST /vaults/{vaultId}/audit/export ─────────────────────────────────────

/**
 * Exports audit logs as CSV for compliance reporting.
 *
 * Request body:
 * - startDate: ISO timestamp for export range start (required)
 * - endDate: ISO timestamp for export range end (required)
 * - userId: Optional filter by user
 * - actions: Optional array of action types to include
 * - format: 'csv' (default) or 'json'
 *
 * @param event - API Gateway event with export parameters in body
 * @param user - Authenticated admin user
 * @param requestId - Request ID for tracing
 * @returns CSV-formatted audit log data
 */
async function handleExport(
  event: APIGatewayProxyEvent,
  user: UserContext,
  vaultId: string,
  requestId: string
): Promise<APIGatewayProxyResult> {
  const body = parseBody(event);
  const now = new Date();
  const retentionWindow = await applyRetentionWindow(
    user.orgId,
    normalizeStartTimestamp(body.startDate as string | undefined)
      || new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    normalizeEndTimestamp(body.endDate as string | undefined)
      || now.toISOString()
  );
  const startDate = retentionWindow.startDate
    || new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000).toISOString();
  const endDate = retentionWindow.endDate || now.toISOString();
  const filterUserId = body.userId as string | undefined;
  const search = body.search as string | undefined;
  const resourcePath = body.path as string | undefined;
  const filterAction = body.action as string | undefined;
  const filterActions = body.actions as string[] | undefined;
  const outcome = body.outcome as AuditQueryFilters['outcome'] | undefined;
  const format = (body.format as string) || 'csv';

  // Validate dates
  if (isNaN(new Date(startDate).getTime()) || isNaN(new Date(endDate).getTime())) {
    return formatError(400, 'Invalid date format. Use ISO 8601.', requestId);
  }
  const query = buildVaultAuditQuery(user.orgId, vaultId, {
    search,
    userId: filterUserId,
    action: filterAction,
    resourcePath,
    outcome,
    startDate,
    endDate,
  });
  let allEntries = await queryAllAuditEntries({
    indexName: 'vaultId-index',
    keyConditionExpression: query.keyConditionExpression,
    expressionAttributeValues: query.expressionAttributeValues,
    expressionAttributeNames: query.expressionAttributeNames,
    filterExpression: query.filterExpression,
  });

  // Apply action filter if provided
  if (filterActions && filterActions.length > 0) {
    allEntries = allEntries.filter((e) => filterActions.includes(e.action));
  }

  // Sort chronologically
  allEntries.sort((a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime());

  // Log the export action
  await logAudit({
    userId: user.userId,
    userEmail: user.email,
    orgId: user.orgId,
    vaultId,
    action: 'audit.export',
    resourcePath: `/vaults/${vaultId}/audit/export`,
    outcome: 'success',
    ipAddress: getClientIp(event),
    userAgent: getUserAgent(event),
    metadata: {
      startDate,
      endDate,
      vaultId,
      entryCount: allEntries.length,
      format,
      search,
      resourcePath,
      filterUserId,
      filterAction,
      filterActions,
      outcome,
    },
  });

  if (format === 'json') {
    return formatSuccess(
      200,
      {
        entries: allEntries,
        count: allEntries.length,
        exportedAt: new Date().toISOString(),
        range: { startDate, endDate },
      },
      requestId
    );
  }

  // Generate CSV
  const csv = generateCsv(allEntries);

  return {
    statusCode: 200,
    headers: {
      'Content-Type': 'text/csv',
      'Content-Disposition': `attachment; filename="audit-log-${startDate.split('T')[0]}-to-${endDate.split('T')[0]}.csv"`,
      'Access-Control-Allow-Origin': ALLOWED_CORS_ORIGIN,
      'Access-Control-Allow-Headers': 'Content-Type,Authorization,X-VaultGuard-Session-Id',
      'Access-Control-Allow-Methods': 'GET,POST,PUT,PATCH,DELETE,OPTIONS',
      'X-Request-Id': requestId,
    },
    body: csv,
  };
}

// ─── Anomaly Detection ───────────────────────────────────────────────────────

/**
 * Runs real-time anomaly detection against recent audit log entries.
 * Checks for:
 * 1. Revoked users attempting access
 * 2. Bulk download patterns (many reads in short window)
 * 3. Repeated permission denials for same user
 * 4. Access during unusual hours
 *
 * @returns Array of newly detected security alerts
 */
async function detectAnomalies(user: UserContext, vaultId: string): Promise<SecurityAlert[]> {
  const windowStart = new Date(Date.now() - ANOMALY_WINDOW_MINUTES * 60 * 1000).toISOString();
  const recentEntries = await queryAllAuditEntries({
    indexName: 'vaultId-index',
    keyConditionExpression: 'vaultId = :vaultId AND #ts >= :windowStart',
    expressionAttributeValues: {
      ':vaultId': vaultId,
      ':orgId': user.orgId,
      ':windowStart': windowStart,
    },
    expressionAttributeNames: {
      '#ts': 'timestamp',
    },
    filterExpression: 'orgId = :orgId',
  });
  const windowBucket = Math.floor(Date.now() / (ANOMALY_WINDOW_MINUTES * 60 * 1000));
  const alerts: SecurityAlert[] = [];

  // Detect: Repeated permission denials
  const denialsByUser = new Map<string, AuditEntry[]>();
  for (const entry of recentEntries) {
    if (entry.outcome === 'denied') {
      const existing = denialsByUser.get(entry.userId) || [];
      existing.push(entry);
      denialsByUser.set(entry.userId, existing);
    }
  }

  for (const [userId, denials] of denialsByUser) {
    if (denials.length >= ANOMALY_THRESHOLD_DENIED) {
      alerts.push({
        id: buildAlertId('repeated_denial', user.orgId, vaultId, userId, String(windowBucket)),
        orgId: user.orgId,
        vaultId,
        type: 'repeated_denial',
        severity: denials.length >= ANOMALY_THRESHOLD_DENIED * 2 ? 'high' : 'medium',
        userId,
        description: `User ${userId} received ${denials.length} permission denials in the last ${ANOMALY_WINDOW_MINUTES} minutes`,
        timestamp: new Date().toISOString(),
        metadata: {
          denialCount: denials.length,
          vaultId,
          paths: [...new Set(denials.map((d) => d.resourcePath))],
          actions: [...new Set(denials.map((d) => d.action))],
        },
        acknowledged: false,
      });
    }
  }

  // Detect: Bulk downloads
  const readsByUser = new Map<string, AuditEntry[]>();
  for (const entry of recentEntries) {
    if (entry.action === 'files.read' && entry.outcome === 'success') {
      const existing = readsByUser.get(entry.userId) || [];
      existing.push(entry);
      readsByUser.set(entry.userId, existing);
    }
  }

  for (const [userId, reads] of readsByUser) {
    if (reads.length >= ANOMALY_THRESHOLD_BULK) {
      alerts.push({
        id: buildAlertId('bulk_download', user.orgId, vaultId, userId, String(windowBucket)),
        orgId: user.orgId,
        vaultId,
        type: 'bulk_download',
        severity: 'high',
        userId,
        description: `User ${userId} read ${reads.length} files in the last ${ANOMALY_WINDOW_MINUTES} minutes (threshold: ${ANOMALY_THRESHOLD_BULK})`,
        timestamp: new Date().toISOString(),
        metadata: {
          readCount: reads.length,
          vaultId,
          uniquePaths: [...new Set(reads.map((r) => r.resourcePath))].length,
        },
        acknowledged: false,
      });
    }
  }

  // Detect: Revoked user access attempts
  const revokedAttempts = recentEntries.filter(
    (e) => e.action === 'auth.key-lease.denied' && e.metadata?.reason === 'keys_revoked'
  );

  for (const attempt of revokedAttempts) {
    alerts.push({
      id: buildAlertId('revoked_access_attempt', user.orgId, vaultId, attempt.id),
      orgId: user.orgId,
      vaultId,
      type: 'revoked_access_attempt',
      severity: 'critical',
      userId: attempt.userId,
      description: `Revoked user ${attempt.userId} attempted to obtain key lease`,
      timestamp: attempt.timestamp,
      metadata: {
        ipAddress: attempt.ipAddress,
        userAgent: attempt.userAgent,
        vaultId,
      },
      acknowledged: false,
    });
  }

  // Detect: Access outside normal hours
  const offHoursByUser = new Map<string, AuditEntry[]>();
  for (const entry of recentEntries) {
    if (entry.outcome !== 'success' || !isAccessAction(entry.action) || !isOffHours(entry.timestamp)) {
      continue;
    }

    const existing = offHoursByUser.get(entry.userId) || [];
    existing.push(entry);
    offHoursByUser.set(entry.userId, existing);
  }

  for (const [userId, entries] of offHoursByUser) {
    alerts.push({
      id: buildAlertId('off_hours_access', user.orgId, vaultId, userId, String(windowBucket)),
      orgId: user.orgId,
      vaultId,
      type: 'off_hours_access',
      severity: entries.length >= 3 ? 'medium' : 'low',
      userId,
      description: `User ${userId} performed ${entries.length} successful access actions outside normal hours`,
      timestamp: entries[0].timestamp,
      metadata: {
        actionCount: entries.length,
        vaultId,
        actions: [...new Set(entries.map((entry) => entry.action))],
        paths: [...new Set(entries.map((entry) => entry.resourcePath).filter(Boolean))].slice(0, 10),
      },
      acknowledged: false,
    });
  }

  // Detect: Unusual access patterns (many IPs or broad resource spread)
  const recentActivityByUser = new Map<string, AuditEntry[]>();
  for (const entry of recentEntries) {
    if (entry.outcome !== 'success') {
      continue;
    }

    const existing = recentActivityByUser.get(entry.userId) || [];
    existing.push(entry);
    recentActivityByUser.set(entry.userId, existing);
  }

  for (const [userId, entries] of recentActivityByUser) {
    const uniqueIps = [...new Set(entries.map((entry) => entry.ipAddress).filter(Boolean))];
    const uniquePaths = [...new Set(entries.map((entry) => entry.resourcePath).filter(Boolean))];
    const uniqueActions = [...new Set(entries.map((entry) => entry.action))];
    const triggeredByIps = uniqueIps.length >= ANOMALY_THRESHOLD_DISTINCT_IPS;
    const triggeredByBreadth =
      uniquePaths.length >= ANOMALY_THRESHOLD_DISTINCT_PATHS && uniqueActions.length >= 4;

    if (!triggeredByIps && !triggeredByBreadth) {
      continue;
    }

    alerts.push({
      id: buildAlertId('unusual_pattern', user.orgId, vaultId, userId, String(windowBucket)),
      orgId: user.orgId,
      vaultId,
      type: 'unusual_pattern',
      severity: triggeredByIps && uniqueIps.length >= ANOMALY_THRESHOLD_DISTINCT_IPS + 1 ? 'high' : 'medium',
      userId,
      description: triggeredByIps
        ? `User ${userId} accessed the vault from ${uniqueIps.length} IPs in ${ANOMALY_WINDOW_MINUTES} minutes`
        : `User ${userId} touched ${uniquePaths.length} unique resources across ${uniqueActions.length} action types in ${ANOMALY_WINDOW_MINUTES} minutes`,
      timestamp: entries[0].timestamp,
      metadata: {
        uniqueIps,
        vaultId,
        uniquePathCount: uniquePaths.length,
        uniqueActions,
      },
      acknowledged: false,
    });
  }

  for (const alert of alerts) {
    await persistAlert(alert);
  }

  return alerts;
}

// ─── Helper Functions ────────────────────────────────────────────────────────

function clampLimit(rawLimit: string | undefined, fallback: number, max: number): number {
  const parsed = parseInt(rawLimit || String(fallback), 10);
  if (Number.isNaN(parsed) || parsed <= 0) {
    return fallback;
  }
  return Math.min(parsed, max);
}

function normalizeStartTimestamp(value?: string): string | undefined {
  if (!value) return undefined;
  if (/^\d{4}-\d{2}-\d{2}$/.test(value)) {
    return `${value}T00:00:00.000Z`;
  }

  const parsed = new Date(value);
  return Number.isNaN(parsed.getTime()) ? value : parsed.toISOString();
}

function normalizeEndTimestamp(value?: string): string | undefined {
  if (!value) return undefined;
  if (/^\d{4}-\d{2}-\d{2}$/.test(value)) {
    return `${value}T23:59:59.999Z`;
  }

  const parsed = new Date(value);
  return Number.isNaN(parsed.getTime()) ? value : parsed.toISOString();
}

export async function applyRetentionWindow(
  orgId: string,
  startDate?: string,
  endDate?: string
): Promise<{ startDate?: string; endDate?: string }> {
  const settings = await getEffectiveOrgSettings(orgId);
  const orgRetentionDays = settings?.retentionDays ?? DEFAULT_ORG_SETTINGS.retentionDays;
  const retentionDays = FEATURES.advancedAudit
    ? orgRetentionDays
    : Math.min(orgRetentionDays, CE_AUDIT_RETENTION_DAYS);
  const retentionStart = new Date(Date.now() - retentionDays * 24 * 60 * 60 * 1000).toISOString();

  let effectiveStartDate = startDate;
  if (!effectiveStartDate || new Date(effectiveStartDate).getTime() < new Date(retentionStart).getTime()) {
    effectiveStartDate = retentionStart;
  }

  return {
    startDate: effectiveStartDate,
    endDate,
  };
}

function decodeCursor(cursor?: string): Record<string, unknown> | undefined {
  if (!cursor) return undefined;

  try {
    const decoded = Buffer.from(cursor, 'base64url').toString('utf8');
    const parsed = JSON.parse(decoded) as Record<string, unknown>;
    return typeof parsed === 'object' && parsed !== null ? parsed : undefined;
  } catch {
    throw new ValidationError('Invalid cursor');
  }
}

function encodeCursor(lastEvaluatedKey?: Record<string, unknown> | null): string | null {
  if (!lastEvaluatedKey) return null;
  return Buffer.from(JSON.stringify(lastEvaluatedKey), 'utf8').toString('base64url');
}

function buildTimeBoundKeyCondition(
  partitionCondition: string,
  expressionAttributeValues: Record<string, unknown>,
  startDate?: string,
  endDate?: string
): {
  keyConditionExpression: string;
  expressionAttributeValues: Record<string, unknown>;
  expressionAttributeNames?: Record<string, string>;
  filterParts: string[];
} {
  const expressionNames: Record<string, string> = {};
  let keyConditionExpression = partitionCondition;

  if (startDate && endDate) {
    keyConditionExpression += ' AND #ts BETWEEN :startDate AND :endDate';
    expressionAttributeValues[':startDate'] = startDate;
    expressionAttributeValues[':endDate'] = endDate;
    expressionNames['#ts'] = 'timestamp';
  } else if (startDate) {
    keyConditionExpression += ' AND #ts >= :startDate';
    expressionAttributeValues[':startDate'] = startDate;
    expressionNames['#ts'] = 'timestamp';
  } else if (endDate) {
    keyConditionExpression += ' AND #ts <= :endDate';
    expressionAttributeValues[':endDate'] = endDate;
    expressionNames['#ts'] = 'timestamp';
  }

  return {
    keyConditionExpression,
    expressionAttributeValues,
    expressionAttributeNames: Object.keys(expressionNames).length > 0 ? expressionNames : undefined,
    filterParts: [],
  };
}

function buildAuditFilterExpression(
  filters: AuditQueryFilters,
  expressionAttributeValues: Record<string, unknown>,
  expressionAttributeNames: Record<string, string>
): string | undefined {
  const filterParts: string[] = [];

  if (filters.userId) {
    filterParts.push('userId = :userId');
    expressionAttributeValues[':userId'] = filters.userId;
  }

  if (filters.action) {
    filterParts.push('#action = :action');
    expressionAttributeValues[':action'] = filters.action;
    expressionAttributeNames['#action'] = 'action';
  }

  if (filters.resourcePath) {
    filterParts.push('begins_with(resourcePath, :path)');
    expressionAttributeValues[':path'] = filters.resourcePath;
  }

  if (filters.outcome) {
    filterParts.push('outcome = :outcome');
    expressionAttributeValues[':outcome'] = filters.outcome;
  }

  if (filters.search) {
    filterParts.push(
      '(contains(userId, :search) OR contains(resourcePath, :search) OR contains(ipAddress, :search) OR contains(#action, :search) OR contains(userAgent, :search))'
    );
    expressionAttributeValues[':search'] = filters.search;
    expressionAttributeNames['#action'] = 'action';
  }

  return filterParts.length > 0 ? filterParts.join(' AND ') : undefined;
}

function buildVaultAuditQuery(orgId: string, vaultId: string, filters: AuditQueryFilters): {
  keyConditionExpression: string;
  expressionAttributeValues: Record<string, unknown>;
  expressionAttributeNames?: Record<string, string>;
  filterExpression?: string;
} {
  const query = buildTimeBoundKeyCondition(
    'vaultId = :vaultId',
    { ':vaultId': vaultId },
    filters.startDate,
    filters.endDate
  );
  const expressionNames = { ...(query.expressionAttributeNames || {}) };
  query.expressionAttributeValues[':orgId'] = orgId;
  const filterExpression = [
    'orgId = :orgId',
    buildAuditFilterExpression(filters, query.expressionAttributeValues, expressionNames),
  ].filter(Boolean).join(' AND ');

  return {
    keyConditionExpression: query.keyConditionExpression,
    expressionAttributeValues: query.expressionAttributeValues,
    expressionAttributeNames: Object.keys(expressionNames).length > 0 ? expressionNames : undefined,
    filterExpression,
  };
}

async function queryAuditIndex<T>(params: {
  indexName: string;
  keyConditionExpression: string;
  expressionAttributeValues: Record<string, unknown>;
  expressionAttributeNames?: Record<string, string>;
  filterExpression?: string;
  limit: number;
  cursor?: Record<string, unknown>;
}): Promise<PaginatedResult<T>> {
  const items: T[] = [];
  let lastEvaluatedKey = params.cursor;

  do {
    const request: Record<string, unknown> = {
      TableName: AUDIT_TABLE,
      IndexName: params.indexName,
      KeyConditionExpression: params.keyConditionExpression,
      ExpressionAttributeValues: params.expressionAttributeValues,
      Limit: Math.max(1, params.limit - items.length),
      ScanIndexForward: false,
    };

    if (params.filterExpression) {
      request.FilterExpression = params.filterExpression;
    }

    if (params.expressionAttributeNames && Object.keys(params.expressionAttributeNames).length > 0) {
      request.ExpressionAttributeNames = params.expressionAttributeNames;
    }

    if (lastEvaluatedKey) {
      request.ExclusiveStartKey = lastEvaluatedKey;
    }

    const result = await docClient.send(new QueryCommand(request as any));
    items.push(...((result.Items || []) as T[]));
    lastEvaluatedKey = result.LastEvaluatedKey as Record<string, unknown> | undefined;
  } while (items.length < params.limit && lastEvaluatedKey);

  return {
    items,
    nextCursor: encodeCursor(lastEvaluatedKey),
    lastEvaluatedKey: lastEvaluatedKey || null,
  };
}

async function queryAllAuditEntries(params: {
  indexName: string;
  keyConditionExpression: string;
  expressionAttributeValues: Record<string, unknown>;
  expressionAttributeNames?: Record<string, string>;
  filterExpression?: string;
}): Promise<AuditEntry[]> {
  const items: AuditEntry[] = [];
  let lastEvaluatedKey: Record<string, unknown> | undefined;

  do {
    const request: Record<string, unknown> = {
      TableName: AUDIT_TABLE,
      IndexName: params.indexName,
      KeyConditionExpression: params.keyConditionExpression,
      ExpressionAttributeValues: params.expressionAttributeValues,
      ScanIndexForward: false,
    };

    if (params.filterExpression) {
      request.FilterExpression = params.filterExpression;
    }

    if (params.expressionAttributeNames && Object.keys(params.expressionAttributeNames).length > 0) {
      request.ExpressionAttributeNames = params.expressionAttributeNames;
    }

    if (lastEvaluatedKey) {
      request.ExclusiveStartKey = lastEvaluatedKey;
    }

    const result = await docClient.send(new QueryCommand(request as any));
    items.push(...((result.Items || []) as AuditEntry[]));
    lastEvaluatedKey = result.LastEvaluatedKey as Record<string, unknown> | undefined;
  } while (lastEvaluatedKey);

  return items;
}

async function queryAlerts(params: {
  expressionAttributeValues: Record<string, unknown>;
  expressionAttributeNames?: Record<string, string>;
  filterExpression?: string;
  limit: number;
  cursor?: Record<string, unknown>;
}): Promise<PaginatedResult<SecurityAlert>> {
  const items: SecurityAlert[] = [];
  let lastEvaluatedKey = params.cursor;

  do {
    const request: Record<string, unknown> = {
      TableName: ALERTS_TABLE,
      IndexName: 'orgId-index',
      KeyConditionExpression: 'orgId = :orgId',
      ExpressionAttributeValues: params.expressionAttributeValues,
      Limit: Math.max(1, params.limit - items.length),
      ScanIndexForward: false,
    };

    if (params.filterExpression) {
      request.FilterExpression = params.filterExpression;
    }

    if (params.expressionAttributeNames && Object.keys(params.expressionAttributeNames).length > 0) {
      request.ExpressionAttributeNames = params.expressionAttributeNames;
    }

    if (lastEvaluatedKey) {
      request.ExclusiveStartKey = lastEvaluatedKey;
    }

    const result = await docClient.send(new QueryCommand(request as any));
    items.push(...((result.Items || []) as SecurityAlert[]));
    lastEvaluatedKey = result.LastEvaluatedKey as Record<string, unknown> | undefined;
  } while (items.length < params.limit && lastEvaluatedKey);

  return {
    items,
    nextCursor: encodeCursor(lastEvaluatedKey),
    lastEvaluatedKey: lastEvaluatedKey || null,
  };
}

function sortAlerts(alerts: SecurityAlert[]): SecurityAlert[] {
  const severityOrder: Record<string, number> = { critical: 0, high: 1, medium: 2, low: 3 };
  return [...alerts].sort((a, b) => {
    const timeDiff = new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime();
    if (timeDiff !== 0) return timeDiff;
    return (severityOrder[a.severity] || 4) - (severityOrder[b.severity] || 4);
  });
}

function buildAlertId(...parts: string[]): string {
  const seed = parts.join('|');
  return `alert_${Buffer.from(seed, 'utf8').toString('base64url').slice(0, 180)}`;
}

async function persistAlert(alert: SecurityAlert): Promise<void> {
  try {
    await docClient.send(new PutCommand({
      TableName: ALERTS_TABLE,
      Item: alert,
      ConditionExpression: 'attribute_not_exists(id)',
    }));
  } catch (err) {
    const errorName = (err as { name?: string }).name;
    if (errorName !== 'ConditionalCheckFailedException') {
      console.error('[AUDIT_ALERT_PERSIST_ERROR]', (err as Error).message, {
        alertId: alert.id,
        type: alert.type,
      });
    }
  }
}

function isAccessAction(action: string): boolean {
  return (
    action.startsWith('files.')
    || action === 'auth.login'
    || action === 'auth.key-lease.issued'
    || action === 'auth.key-lease.scoped'
  );
}

function isOffHours(timestamp: string): boolean {
  const hour = new Date(timestamp).getUTCHours();

  if (OFF_HOURS_START_HOUR_UTC === OFF_HOURS_END_HOUR_UTC) {
    return false;
  }

  if (OFF_HOURS_START_HOUR_UTC < OFF_HOURS_END_HOUR_UTC) {
    return hour >= OFF_HOURS_START_HOUR_UTC && hour < OFF_HOURS_END_HOUR_UTC;
  }

  return hour >= OFF_HOURS_START_HOUR_UTC || hour < OFF_HOURS_END_HOUR_UTC;
}

/**
 * Generates a CSV string from audit log entries.
 *
 * @param entries - Array of audit entries to serialize
 * @returns CSV-formatted string with header row
 */
function generateCsv(entries: AuditEntry[]): string {
  const headers = ['id', 'timestamp', 'vaultId', 'userId', 'userEmail', 'action', 'resourcePath', 'outcome', 'ipAddress', 'userAgent', 'metadata'];
  const rows = entries.map((entry) => {
    return [
      escapeCsvField(entry.id),
      escapeCsvField(entry.timestamp),
      escapeCsvField(entry.vaultId || ''),
      escapeCsvField(entry.userId),
      escapeCsvField(entry.userEmail || ''),
      escapeCsvField(entry.action),
      escapeCsvField(entry.resourcePath),
      escapeCsvField(entry.outcome),
      escapeCsvField(entry.ipAddress || ''),
      escapeCsvField(entry.userAgent || ''),
      escapeCsvField(entry.metadata ? JSON.stringify(entry.metadata) : ''),
    ].join(',');
  });

  return [headers.join(','), ...rows].join('\n');
}

/**
 * Escapes a field value for CSV output.
 * Wraps in quotes if the value contains commas, quotes, or newlines.
 *
 * @param field - The field value to escape
 * @returns Properly escaped CSV field
 */
function escapeCsvField(field: string): string {
  if (field.includes(',') || field.includes('"') || field.includes('\n')) {
    return `"${field.replace(/"/g, '""')}"`;
  }
  return field;
}

/**
 * Generates an activity summary from audit entries.
 * Groups actions by type and calculates statistics.
 *
 * @param entries - Array of audit entries for a user
 * @returns Summary object with action counts and patterns
 */
function generateActivitySummary(entries: AuditEntry[]): Record<string, unknown> {
  const actionCounts = entries.reduce((acc, e) => {
    acc[e.action] = (acc[e.action] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  const outcomeCounts = entries.reduce((acc, e) => {
    acc[e.outcome] = (acc[e.outcome] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  const uniquePaths = [...new Set(entries.map((e) => e.resourcePath))];
  const uniqueIps = [...new Set(entries.filter((e) => e.ipAddress).map((e) => e.ipAddress!))];

  const firstActivity = entries.length > 0
    ? entries[entries.length - 1].timestamp
    : null;
  const lastActivity = entries.length > 0
    ? entries[0].timestamp
    : null;

  return {
    totalActions: entries.length,
    actionBreakdown: actionCounts,
    outcomeBreakdown: outcomeCounts,
    uniquePathsAccessed: uniquePaths.length,
    uniqueIpAddresses: uniqueIps,
    firstActivity,
    lastActivity,
    denialRate: entries.length > 0
      ? ((outcomeCounts['denied'] || 0) / entries.length * 100).toFixed(1) + '%'
      : '0%',
  };
}
