# ─────────────────────────────────────────────────────────────────────────────
# DNS & Certificate Module
#
# Manages the Route53 hosted zone, ACM certificates (regional + CloudFront),
# DNS validation records, and subdomain aliases for all VaultGuard services.
#
# Domain layout:
#   example.com            → Landing page (CloudFront)
#   api.example.com        → API Gateway custom domain
#   admin.example.com      → Admin panel (CloudFront)
#   auth.example.com       → Cognito custom domain (future)
# ─────────────────────────────────────────────────────────────────────────────

terraform {
  required_providers {
    aws = {
      source                = "hashicorp/aws"
      configuration_aliases = [aws, aws.us_east_1]
    }
  }
}

variable "stage" { type = string }
variable "domain_name" {
  type        = string
  description = "Root domain (e.g., example.com)"
}

# ─────────────────────────────────────────────────────────────────────────────
# Google Workspace inbound mail
# ─────────────────────────────────────────────────────────────────────────────
# Inbound mail for example.com is handled by Google Workspace.
# Outbound transactional mail (signup, password reset, invoices) continues to
# go through Amazon SES — see the SES section below. The SPF record authorises
# both senders; MX points at Google only.

variable "google_workspace_verification_token" {
  type        = string
  description = "Google site verification token (the value after 'google-site-verification='). Get it from admin.google.com when provisioning the Workspace tenant. Leave empty to skip."
  default     = ""
}

variable "google_workspace_dkim_selector" {
  type        = string
  description = "DKIM selector configured in Google Workspace Admin (Apps → Google Workspace → Gmail → Authenticate email). Default 'google' matches Google's default."
  default     = "google"
}

variable "google_workspace_dkim_value" {
  type        = string
  description = "DKIM public key TXT value generated by Google Workspace Admin (the full string starting with 'v=DKIM1; k=rsa; p=...'). Leave empty to skip until the key is generated."
  default     = ""
}

# ─────────────────────────────────────────────────────────────────────────────
# Route53 Hosted Zone
# ─────────────────────────────────────────────────────────────────────────────

# Import the existing hosted zone (already created in AWS console)
data "aws_route53_zone" "main" {
  name         = var.domain_name
  private_zone = false
}

# ─────────────────────────────────────────────────────────────────────────────
# ACM Certificate — CloudFront (must be us-east-1)
# ─────────────────────────────────────────────────────────────────────────────

# CloudFront requires certificates in us-east-1
resource "aws_acm_certificate" "cloudfront" {
  provider = aws.us_east_1

  domain_name = var.domain_name
  subject_alternative_names = [
    "*.${var.domain_name}",
  ]
  validation_method = "DNS"

  lifecycle {
    create_before_destroy = true
  }

  tags = {
    Name = "vaultguard-cloudfront-${var.stage}"
  }
}

# DNS validation records for the CloudFront certificate
resource "aws_route53_record" "cloudfront_cert_validation" {
  for_each = {
    for dvo in aws_acm_certificate.cloudfront.domain_validation_options : dvo.domain_name => {
      name   = dvo.resource_record_name
      record = dvo.resource_record_value
      type   = dvo.resource_record_type
    }
  }

  zone_id = data.aws_route53_zone.main.zone_id
  name    = each.value.name
  type    = each.value.type
  ttl     = 300
  records = [each.value.record]

  allow_overwrite = true
}

resource "aws_acm_certificate_validation" "cloudfront" {
  provider = aws.us_east_1

  certificate_arn         = aws_acm_certificate.cloudfront.arn
  validation_record_fqdns = [for record in aws_route53_record.cloudfront_cert_validation : record.fqdn]
}

# ─────────────────────────────────────────────────────────────────────────────
# ACM Certificate — Regional (API Gateway, ALBs, etc.)
# ─────────────────────────────────────────────────────────────────────────────

resource "aws_acm_certificate" "regional" {
  domain_name = var.domain_name
  subject_alternative_names = [
    "*.${var.domain_name}",
  ]
  validation_method = "DNS"

  lifecycle {
    create_before_destroy = true
  }

  tags = {
    Name = "vaultguard-regional-${var.stage}"
  }
}

# DNS validation records for the regional certificate
# The wildcard cert shares the same CNAME validation record as the apex,
# so we reuse the cloudfront validation records (same zone, same CNAME).
resource "aws_acm_certificate_validation" "regional" {
  certificate_arn         = aws_acm_certificate.regional.arn
  validation_record_fqdns = [for record in aws_route53_record.cloudfront_cert_validation : record.fqdn]
}

# ─────────────────────────────────────────────────────────────────────────────
# API Gateway Custom Domain
# ─────────────────────────────────────────────────────────────────────────────

resource "aws_api_gateway_domain_name" "api" {
  domain_name              = "api.${var.domain_name}"
  regional_certificate_arn = aws_acm_certificate_validation.regional.certificate_arn

  endpoint_configuration {
    types = ["REGIONAL"]
  }

  security_policy = "TLS_1_2"

  tags = {
    Name = "vaultguard-api-${var.stage}"
  }
}

# ─────────────────────────────────────────────────────────────────────────────
# DNS Records — Point subdomains to AWS services
# ─────────────────────────────────────────────────────────────────────────────

# api.example.com → API Gateway custom domain
resource "aws_route53_record" "api" {
  zone_id = data.aws_route53_zone.main.zone_id
  name    = "api.${var.domain_name}"
  type    = "A"

  alias {
    name                   = aws_api_gateway_domain_name.api.regional_domain_name
    zone_id                = aws_api_gateway_domain_name.api.regional_zone_id
    evaluate_target_health = false
  }
}

# NOTE: example.com (apex), admin.example.com, and
# share.example.com DNS records are managed by Amplify Hosting via
# `aws_amplify_domain_association` set up in the AWS console (mirrors the
# landing/admin pattern). Do NOT create them here or they will conflict.

# MX record — Google Workspace handles all inbound mail.
# SES is NOT in the MX set: outbound from SES doesn't need an MX, and adding
# SES as a low-priority fallback would silently drop mail (no SES receipt rule
# is configured) whenever Google has a hiccup.
resource "aws_route53_record" "mx" {
  zone_id = data.aws_route53_zone.main.zone_id
  name    = var.domain_name
  type    = "MX"
  ttl     = 3600
  records = ["1 SMTP.GOOGLE.COM."]
}

# Google site-verification TXT — required to claim the domain inside the
# Workspace admin console. The token is short-lived during setup but can
# stay in DNS afterwards without harm.
#
# This record co-exists at the apex with the SPF record (a separate TXT
# resource); both are valid because DNS allows multiple TXT records on the
# same name. allow_overwrite=true lets Terraform adopt a record that was
# created manually in the Route53 console first.
resource "aws_route53_record" "google_site_verification" {
  count = var.google_workspace_verification_token == "" ? 0 : 1

  zone_id         = data.aws_route53_zone.main.zone_id
  name            = var.domain_name
  type            = "TXT"
  ttl             = 600
  records         = ["google-site-verification=${var.google_workspace_verification_token}"]
  allow_overwrite = true
}

# Google Workspace DKIM — the public key is generated in the Workspace admin
# console (Apps → Google Workspace → Gmail → Authenticate email). Paste the
# resulting value into google_workspace_dkim_value as a single continuous
# string (no embedded "" splits) — we re-chunk below.
#
# DNS TXT records are made of one or more "character-strings", each at most
# 255 bytes (RFC 1035 §3.3.14). Resolvers concatenate them. Google's DKIM
# public key exceeds 255 bytes, so we split into 255-char chunks and join
# them with `" "` (literal quote-space-quote). The AWS provider auto-wraps
# the whole TXT value in outer quotes, yielding the canonical multi-string
# wire format `"chunk1" "chunk2"` that Route53 expects. (Adding our own
# outer quotes here would produce `""chunk1" "chunk2""` and Route53 rejects
# it as InvalidCharacterString.)
locals {
  _google_dkim_chunks = var.google_workspace_dkim_value == "" ? [] : [
    for i in range(0, length(var.google_workspace_dkim_value), 255) :
    substr(var.google_workspace_dkim_value, i, min(255, length(var.google_workspace_dkim_value) - i))
  ]
  google_dkim_record_value = join("\" \"", local._google_dkim_chunks)
}

resource "aws_route53_record" "google_dkim" {
  count = var.google_workspace_dkim_value == "" ? 0 : 1

  zone_id         = data.aws_route53_zone.main.zone_id
  name            = "${var.google_workspace_dkim_selector}._domainkey.${var.domain_name}"
  type            = "TXT"
  ttl             = 600
  records         = [local.google_dkim_record_value]
  allow_overwrite = true
}

# ─────────────────────────────────────────────────────────────────────────────
# SES Domain Verification (DKIM + SPF)
# ─────────────────────────────────────────────────────────────────────────────

resource "aws_ses_domain_identity" "main" {
  domain = var.domain_name
}

resource "aws_ses_domain_dkim" "main" {
  domain = aws_ses_domain_identity.main.domain
}

# DKIM CNAME records (3 records for SES DKIM verification)
resource "aws_route53_record" "ses_dkim" {
  count = 3

  zone_id = data.aws_route53_zone.main.zone_id
  name    = "${aws_ses_domain_dkim.main.dkim_tokens[count.index]}._domainkey.${var.domain_name}"
  type    = "CNAME"
  ttl     = 600
  records = ["${aws_ses_domain_dkim.main.dkim_tokens[count.index]}.dkim.amazonses.com"]
}

# SES domain verification TXT record
resource "aws_route53_record" "ses_verification" {
  zone_id = data.aws_route53_zone.main.zone_id
  name    = "_amazonses.${var.domain_name}"
  type    = "TXT"
  ttl     = 600
  records = [aws_ses_domain_identity.main.verification_token]
}

# SPF record — authorise both Google Workspace (human mail via Gmail) and
# Amazon SES (transactional mail from the app) to send from this domain.
# A domain may only have ONE SPF TXT record; both senders must share it.
resource "aws_route53_record" "spf" {
  zone_id = data.aws_route53_zone.main.zone_id
  name    = var.domain_name
  type    = "TXT"
  ttl     = 600
  records = ["v=spf1 include:_spf.google.com include:amazonses.com -all"]
}

# DMARC record — email authentication policy
resource "aws_route53_record" "dmarc" {
  zone_id = data.aws_route53_zone.main.zone_id
  name    = "_dmarc.${var.domain_name}"
  type    = "TXT"
  ttl     = 600
  records = ["v=DMARC1; p=quarantine; rua=mailto:dmarc@${var.domain_name}; pct=100"]
}

# ─────────────────────────────────────────────────────────────────────────────
# Outputs
# ─────────────────────────────────────────────────────────────────────────────

output "zone_id" {
  value = data.aws_route53_zone.main.zone_id
}

output "cloudfront_certificate_arn" {
  description = "ACM certificate ARN for CloudFront (us-east-1)"
  value       = aws_acm_certificate_validation.cloudfront.certificate_arn
}

output "regional_certificate_arn" {
  description = "ACM certificate ARN for API Gateway and regional services"
  value       = aws_acm_certificate_validation.regional.certificate_arn
}

output "api_custom_domain" {
  description = "API Gateway custom domain name"
  value       = aws_api_gateway_domain_name.api.domain_name
}

output "api_gateway_domain_name" {
  description = "API Gateway regional target domain (for base path mapping)"
  value       = aws_api_gateway_domain_name.api.regional_domain_name
}

output "nameservers" {
  description = "Nameservers to configure at your domain registrar"
  value       = data.aws_route53_zone.main.name_servers
}
